# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import AsrService_pb2 as AsrService__pb2
import base_pb2 as base__pb2


class SpeechRecognitionStub(object):
  """*
  Сервис распознавания речи
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetListOfSpeechRecognitionModels = channel.unary_unary(
        '/Speechpro.Cloud.ASR.SpeechRecognition/GetListOfSpeechRecognitionModels',
        request_serializer=AsrService__pb2.Auth.SerializeToString,
        response_deserializer=base__pb2.ListOfModels.FromString,
        )
    self.RecognizeSpeech = channel.stream_stream(
        '/Speechpro.Cloud.ASR.SpeechRecognition/RecognizeSpeech',
        request_serializer=AsrService__pb2.RecognizeRequest.SerializeToString,
        response_deserializer=AsrService__pb2.SpeechRecognitionResults.FromString,
        )


class SpeechRecognitionServicer(object):
  """*
  Сервис распознавания речи
  """

  def GetListOfSpeechRecognitionModels(self, request, context):
    """Получить список доступных моделей для распознавания речи
    Получить количество запущенных сессий по конкретной модели
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecognizeSpeech(self, request_iterator, context):
    """Распознать речь.
    Пользователь отправляет поток запросов на распознавание и получает поток результатов распознавания от сервиса
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SpeechRecognitionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetListOfSpeechRecognitionModels': grpc.unary_unary_rpc_method_handler(
          servicer.GetListOfSpeechRecognitionModels,
          request_deserializer=AsrService__pb2.Auth.FromString,
          response_serializer=base__pb2.ListOfModels.SerializeToString,
      ),
      'RecognizeSpeech': grpc.stream_stream_rpc_method_handler(
          servicer.RecognizeSpeech,
          request_deserializer=AsrService__pb2.RecognizeRequest.FromString,
          response_serializer=AsrService__pb2.SpeechRecognitionResults.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Speechpro.Cloud.ASR.SpeechRecognition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
