# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='Speechpro',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbase.proto\x12\tSpeechpro\",\n\x05Model\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0f\x61\x63tive_sessions\x18\x02 \x01(\x04\"0\n\x0cListOfModels\x12 \n\x06models\x18\x01 \x03(\x0b\x32\x10.Speechpro.Model\"\x08\n\x06\x46inish\"&\n\x04Text\x12\x1e\n\x05words\x18\x01 \x03(\x0b\x32\x0f.Speechpro.Word\"\xc3\x02\n\x04Word\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08start_ms\x18\x02 \x01(\x03\x12\x11\n\tlength_ms\x18\x03 \x01(\x03\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x39\n\x10punctuation_mark\x18\x05 \x01(\x0e\x32\x1f.Speechpro.Word.PunctuationMark\x12%\n\x06\x64ictor\x18\x06 \x01(\x0b\x32\x15.Speechpro.DictorInfo\"\x91\x01\n\x0fPunctuationMark\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x44OT\x10\x01\x12\t\n\x05\x43OMMA\x10\x02\x12\t\n\x05\x43OLON\x10\x03\x12\r\n\tSEMICOLON\x10\x04\x12\x15\n\x11\x45XCLAMATION_POINT\x10\x05\x12\x11\n\rQUESTION_MARK\x10\x06\x12\x08\n\x04\x44\x41SH\x10\x07\x12\x12\n\x0eSPEAKER_CHANGE\x10\x08\"\xa2\x01\n\nDictorInfo\x12\x46\n\x13\x64ictor_not_detected\x18\x01 \x01(\x0e\x32\'.Speechpro.DictorInfo.DictorNotDetectedH\x00\x12\x14\n\ndictor_num\x18\x02 \x01(\x05H\x00\"\'\n\x11\x44ictorNotDetected\x12\x12\n\x0eUNKNOWN_DICTOR\x10\x00\x42\r\n\x0b\x64ictor_infob\x06proto3')
)



_WORD_PUNCTUATIONMARK = _descriptor.EnumDescriptor(
  name='PunctuationMark',
  full_name='Speechpro.Word.PunctuationMark',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMA', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLON', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEMICOLON', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCLAMATION_POINT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUESTION_MARK', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DASH', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPEAKER_CHANGE', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=350,
  serialized_end=495,
)
_sym_db.RegisterEnumDescriptor(_WORD_PUNCTUATIONMARK)

_DICTORINFO_DICTORNOTDETECTED = _descriptor.EnumDescriptor(
  name='DictorNotDetected',
  full_name='Speechpro.DictorInfo.DictorNotDetected',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_DICTOR', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=606,
  serialized_end=645,
)
_sym_db.RegisterEnumDescriptor(_DICTORINFO_DICTORNOTDETECTED)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Speechpro.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Speechpro.Model.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active_sessions', full_name='Speechpro.Model.active_sessions', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=69,
)


_LISTOFMODELS = _descriptor.Descriptor(
  name='ListOfModels',
  full_name='Speechpro.ListOfModels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='Speechpro.ListOfModels.models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=119,
)


_FINISH = _descriptor.Descriptor(
  name='Finish',
  full_name='Speechpro.Finish',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=129,
)


_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='Speechpro.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='words', full_name='Speechpro.Text.words', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=169,
)


_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='Speechpro.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='Speechpro.Word.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_ms', full_name='Speechpro.Word.start_ms', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_ms', full_name='Speechpro.Word.length_ms', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='Speechpro.Word.confidence', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='punctuation_mark', full_name='Speechpro.Word.punctuation_mark', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dictor', full_name='Speechpro.Word.dictor', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORD_PUNCTUATIONMARK,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=495,
)


_DICTORINFO = _descriptor.Descriptor(
  name='DictorInfo',
  full_name='Speechpro.DictorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dictor_not_detected', full_name='Speechpro.DictorInfo.dictor_not_detected', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dictor_num', full_name='Speechpro.DictorInfo.dictor_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DICTORINFO_DICTORNOTDETECTED,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='dictor_info', full_name='Speechpro.DictorInfo.dictor_info',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=498,
  serialized_end=660,
)

_LISTOFMODELS.fields_by_name['models'].message_type = _MODEL
_TEXT.fields_by_name['words'].message_type = _WORD
_WORD.fields_by_name['punctuation_mark'].enum_type = _WORD_PUNCTUATIONMARK
_WORD.fields_by_name['dictor'].message_type = _DICTORINFO
_WORD_PUNCTUATIONMARK.containing_type = _WORD
_DICTORINFO.fields_by_name['dictor_not_detected'].enum_type = _DICTORINFO_DICTORNOTDETECTED
_DICTORINFO_DICTORNOTDETECTED.containing_type = _DICTORINFO
_DICTORINFO.oneofs_by_name['dictor_info'].fields.append(
  _DICTORINFO.fields_by_name['dictor_not_detected'])
_DICTORINFO.fields_by_name['dictor_not_detected'].containing_oneof = _DICTORINFO.oneofs_by_name['dictor_info']
_DICTORINFO.oneofs_by_name['dictor_info'].fields.append(
  _DICTORINFO.fields_by_name['dictor_num'])
_DICTORINFO.fields_by_name['dictor_num'].containing_oneof = _DICTORINFO.oneofs_by_name['dictor_info']
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['ListOfModels'] = _LISTOFMODELS
DESCRIPTOR.message_types_by_name['Finish'] = _FINISH
DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['Word'] = _WORD
DESCRIPTOR.message_types_by_name['DictorInfo'] = _DICTORINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Model)
  })
_sym_db.RegisterMessage(Model)

ListOfModels = _reflection.GeneratedProtocolMessageType('ListOfModels', (_message.Message,), {
  'DESCRIPTOR' : _LISTOFMODELS,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.ListOfModels)
  })
_sym_db.RegisterMessage(ListOfModels)

Finish = _reflection.GeneratedProtocolMessageType('Finish', (_message.Message,), {
  'DESCRIPTOR' : _FINISH,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Finish)
  })
_sym_db.RegisterMessage(Finish)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Text)
  })
_sym_db.RegisterMessage(Text)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {
  'DESCRIPTOR' : _WORD,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Word)
  })
_sym_db.RegisterMessage(Word)

DictorInfo = _reflection.GeneratedProtocolMessageType('DictorInfo', (_message.Message,), {
  'DESCRIPTOR' : _DICTORINFO,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.DictorInfo)
  })
_sym_db.RegisterMessage(DictorInfo)


# @@protoc_insertion_point(module_scope)
