# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AsrService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AsrService.proto',
  package='Speechpro.Cloud.ASR',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x41srService.proto\x12\x13Speechpro.Cloud.ASR\x1a\nbase.proto\"\xb3\x01\n\x10RecognizeRequest\x12\x38\n\x06\x63onfig\x18\x01 \x01(\x0b\x32&.Speechpro.Cloud.ASR.RecognitionConfigH\x00\x12+\n\x05sound\x18\x02 \x01(\x0b\x32\x1a.Speechpro.Cloud.ASR.SoundH\x00\x12#\n\x06\x66inish\x18\x03 \x01(\x0b\x32\x11.Speechpro.FinishH\x00\x42\x13\n\x11recognize_request\"\xbd\x01\n\x11RecognitionConfig\x12\x1f\n\x05model\x18\x01 \x01(\x0b\x32\x10.Speechpro.Model\x12\x18\n\x10\x61\x64\x64itional_words\x18\x02 \x03(\t\x12\x44\n\x13user_transcriptions\x18\x03 \x03(\x0b\x32\'.Speechpro.Cloud.ASR.UserTranscriptions\x12\'\n\x04\x61uth\x18\x04 \x01(\x0b\x32\x19.Speechpro.Cloud.ASR.Auth\"=\n\x04\x41uth\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\tdomain_id\x18\x02 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\"9\n\x12UserTranscriptions\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x15\n\rtranscription\x18\x02 \x01(\t\"\x18\n\x05Sound\x12\x0f\n\x07samples\x18\x01 \x01(\x0c\"f\n\x18SpeechRecognitionResults\x12\x1d\n\x04text\x18\x01 \x01(\x0b\x32\x0f.Speechpro.Text\x12\x19\n\x11phrase_confidence\x18\x02 \x01(\x02\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x32\xd8\x01\n\x11SpeechRecognition\x12V\n GetListOfSpeechRecognitionModels\x12\x19.Speechpro.Cloud.ASR.Auth\x1a\x17.Speechpro.ListOfModels\x12k\n\x0fRecognizeSpeech\x12%.Speechpro.Cloud.ASR.RecognizeRequest\x1a-.Speechpro.Cloud.ASR.SpeechRecognitionResults(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[base__pb2.DESCRIPTOR,])




_RECOGNIZEREQUEST = _descriptor.Descriptor(
  name='RecognizeRequest',
  full_name='Speechpro.Cloud.ASR.RecognizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='Speechpro.Cloud.ASR.RecognizeRequest.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sound', full_name='Speechpro.Cloud.ASR.RecognizeRequest.sound', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finish', full_name='Speechpro.Cloud.ASR.RecognizeRequest.finish', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='recognize_request', full_name='Speechpro.Cloud.ASR.RecognizeRequest.recognize_request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=54,
  serialized_end=233,
)


_RECOGNITIONCONFIG = _descriptor.Descriptor(
  name='RecognitionConfig',
  full_name='Speechpro.Cloud.ASR.RecognitionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='Speechpro.Cloud.ASR.RecognitionConfig.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='additional_words', full_name='Speechpro.Cloud.ASR.RecognitionConfig.additional_words', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_transcriptions', full_name='Speechpro.Cloud.ASR.RecognitionConfig.user_transcriptions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='Speechpro.Cloud.ASR.RecognitionConfig.auth', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=425,
)


_AUTH = _descriptor.Descriptor(
  name='Auth',
  full_name='Speechpro.Cloud.ASR.Auth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='Speechpro.Cloud.ASR.Auth.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain_id', full_name='Speechpro.Cloud.ASR.Auth.domain_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_key', full_name='Speechpro.Cloud.ASR.Auth.api_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=488,
)


_USERTRANSCRIPTIONS = _descriptor.Descriptor(
  name='UserTranscriptions',
  full_name='Speechpro.Cloud.ASR.UserTranscriptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='Speechpro.Cloud.ASR.UserTranscriptions.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transcription', full_name='Speechpro.Cloud.ASR.UserTranscriptions.transcription', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=547,
)


_SOUND = _descriptor.Descriptor(
  name='Sound',
  full_name='Speechpro.Cloud.ASR.Sound',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='Speechpro.Cloud.ASR.Sound.samples', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=573,
)


_SPEECHRECOGNITIONRESULTS = _descriptor.Descriptor(
  name='SpeechRecognitionResults',
  full_name='Speechpro.Cloud.ASR.SpeechRecognitionResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='Speechpro.Cloud.ASR.SpeechRecognitionResults.text', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phrase_confidence', full_name='Speechpro.Cloud.ASR.SpeechRecognitionResults.phrase_confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_final', full_name='Speechpro.Cloud.ASR.SpeechRecognitionResults.is_final', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=677,
)

_RECOGNIZEREQUEST.fields_by_name['config'].message_type = _RECOGNITIONCONFIG
_RECOGNIZEREQUEST.fields_by_name['sound'].message_type = _SOUND
_RECOGNIZEREQUEST.fields_by_name['finish'].message_type = base__pb2._FINISH
_RECOGNIZEREQUEST.oneofs_by_name['recognize_request'].fields.append(
  _RECOGNIZEREQUEST.fields_by_name['config'])
_RECOGNIZEREQUEST.fields_by_name['config'].containing_oneof = _RECOGNIZEREQUEST.oneofs_by_name['recognize_request']
_RECOGNIZEREQUEST.oneofs_by_name['recognize_request'].fields.append(
  _RECOGNIZEREQUEST.fields_by_name['sound'])
_RECOGNIZEREQUEST.fields_by_name['sound'].containing_oneof = _RECOGNIZEREQUEST.oneofs_by_name['recognize_request']
_RECOGNIZEREQUEST.oneofs_by_name['recognize_request'].fields.append(
  _RECOGNIZEREQUEST.fields_by_name['finish'])
_RECOGNIZEREQUEST.fields_by_name['finish'].containing_oneof = _RECOGNIZEREQUEST.oneofs_by_name['recognize_request']
_RECOGNITIONCONFIG.fields_by_name['model'].message_type = base__pb2._MODEL
_RECOGNITIONCONFIG.fields_by_name['user_transcriptions'].message_type = _USERTRANSCRIPTIONS
_RECOGNITIONCONFIG.fields_by_name['auth'].message_type = _AUTH
_SPEECHRECOGNITIONRESULTS.fields_by_name['text'].message_type = base__pb2._TEXT
DESCRIPTOR.message_types_by_name['RecognizeRequest'] = _RECOGNIZEREQUEST
DESCRIPTOR.message_types_by_name['RecognitionConfig'] = _RECOGNITIONCONFIG
DESCRIPTOR.message_types_by_name['Auth'] = _AUTH
DESCRIPTOR.message_types_by_name['UserTranscriptions'] = _USERTRANSCRIPTIONS
DESCRIPTOR.message_types_by_name['Sound'] = _SOUND
DESCRIPTOR.message_types_by_name['SpeechRecognitionResults'] = _SPEECHRECOGNITIONRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognizeRequest = _reflection.GeneratedProtocolMessageType('RecognizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEREQUEST,
  '__module__' : 'AsrService_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Cloud.ASR.RecognizeRequest)
  })
_sym_db.RegisterMessage(RecognizeRequest)

RecognitionConfig = _reflection.GeneratedProtocolMessageType('RecognitionConfig', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONCONFIG,
  '__module__' : 'AsrService_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Cloud.ASR.RecognitionConfig)
  })
_sym_db.RegisterMessage(RecognitionConfig)

Auth = _reflection.GeneratedProtocolMessageType('Auth', (_message.Message,), {
  'DESCRIPTOR' : _AUTH,
  '__module__' : 'AsrService_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Cloud.ASR.Auth)
  })
_sym_db.RegisterMessage(Auth)

UserTranscriptions = _reflection.GeneratedProtocolMessageType('UserTranscriptions', (_message.Message,), {
  'DESCRIPTOR' : _USERTRANSCRIPTIONS,
  '__module__' : 'AsrService_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Cloud.ASR.UserTranscriptions)
  })
_sym_db.RegisterMessage(UserTranscriptions)

Sound = _reflection.GeneratedProtocolMessageType('Sound', (_message.Message,), {
  'DESCRIPTOR' : _SOUND,
  '__module__' : 'AsrService_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Cloud.ASR.Sound)
  })
_sym_db.RegisterMessage(Sound)

SpeechRecognitionResults = _reflection.GeneratedProtocolMessageType('SpeechRecognitionResults', (_message.Message,), {
  'DESCRIPTOR' : _SPEECHRECOGNITIONRESULTS,
  '__module__' : 'AsrService_pb2'
  # @@protoc_insertion_point(class_scope:Speechpro.Cloud.ASR.SpeechRecognitionResults)
  })
_sym_db.RegisterMessage(SpeechRecognitionResults)



_SPEECHRECOGNITION = _descriptor.ServiceDescriptor(
  name='SpeechRecognition',
  full_name='Speechpro.Cloud.ASR.SpeechRecognition',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=680,
  serialized_end=896,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetListOfSpeechRecognitionModels',
    full_name='Speechpro.Cloud.ASR.SpeechRecognition.GetListOfSpeechRecognitionModels',
    index=0,
    containing_service=None,
    input_type=_AUTH,
    output_type=base__pb2._LISTOFMODELS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RecognizeSpeech',
    full_name='Speechpro.Cloud.ASR.SpeechRecognition.RecognizeSpeech',
    index=1,
    containing_service=None,
    input_type=_RECOGNIZEREQUEST,
    output_type=_SPEECHRECOGNITIONRESULTS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECHRECOGNITION)

DESCRIPTOR.services_by_name['SpeechRecognition'] = _SPEECHRECOGNITION

# @@protoc_insertion_point(module_scope)
